# Generated by Django 4.2.13 on 2024-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='client',
            new_name='client_reference_no',
        ),
        migrations.AddField(
            model_name='account',
            name='consumer_address',
            field=models.TextField(default='Unknown Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='ssn',
            field=models.CharField(default='Unknown Address', max_length=11),
            preserve_default=False,
        ),
    ]
